Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMercadoMVC.Models;

namespace WebMercadoMVC.Controllers
{
    [Authorize]
    public class ComprasController : Controller
    {
        private readonly Contexto _context;

        public ComprasController(Contexto context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Compras.Include(c => c.cliente).Include(c => c.produto);
            return View(await contexto.ToListAsync());
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.cliente)
                .Include(c => c.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            ViewData["clienteid"] = new SelectList(_context.Clientes, "id", "email");
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome");
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,clienteid,produtoid,quantidaderequisitada")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                Produto produto = await _context.Produtos.FindAsync(compra.produtoid);
                // Reduzir a quantidade do produto com base na compra
                produto.qtde -= compra.quantidaderequisitada;

                // Multiplicar o preço pelo número de unidades compradas

                float precomult = produto.preco * compra.quantidaderequisitada;

                produto.preco = precomult;

                _context.Update(produto);
                _context.Add(compra);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            ViewData["clienteid"] = new SelectList(_context.Clientes, "id", "email", compra.clienteid);
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", compra.produtoid);
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            ViewData["clienteid"] = new SelectList(_context.Clientes, "id", "email", compra.clienteid);
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", compra.produtoid);
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,clienteid,produtoid,quantidaderequisitada")] Compra compra)
        {
            if (id != compra.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["clienteid"] = new SelectList(_context.Clientes, "id", "email", compra.clienteid);
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", compra.produtoid);
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.cliente)
                .Include(c => c.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'Contexto.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
          return _context.Compras.Any(e => e.id == id);
        }
    }
}

Controllers/DadosController.cs
using WebMercadoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;

namespace MercadoMVC.Controllers
{
    public class DadosController : Controller
    {
        private readonly Contexto contexto;

        public DadosController(Contexto context)
        {
            contexto = context;
        }

        public IActionResult Clientes()
        {
            contexto.Database.ExecuteSqlRaw("delete from clientes");
            contexto.Database.ExecuteSqlRaw("DBCC CHECKIDENT('clientes', RESEED, 0)");
            Random randnum = new Random();

            string[] vNomeMas = { "Almir", "Arthur", "Bruno", "Caio", "Mateus", "Caio Lima", "Mateus Nogueira", "Felipe", "Felipe Ferreira", "Bruno Oliveira" };
            string[] vNomeFem = { "Ana", "Beatriz", "Carla", "Maria", "Sofia", "Ana Maria", "Maria Lima", "Jessica", "Lisa", "Marisa" };
            string[] vEmail = { "email1@gmail.com", "email2@gmail.com", "email3@gmail.com", "email4@gmail.com", "email5@gmail.com" };

            for (int i = 0; i < 20; i++)
            {
                Cliente cliente = new Cliente();

                /*cliente.nome = "Nome " + (i+1).ToString();
                cliente.email = "Email " + (i+1).ToString() + "@gmail.com";*/

                cliente.nome = (i % 2 == 0) ? vNomeMas[i / 2] : vNomeFem[i / 2];
                cliente.email = vEmail[randnum.Next() % 5];
                contexto.Clientes.Add(cliente);
            }
            contexto.SaveChanges();

            return View(contexto.Clientes.OrderBy(o => o.id).ToList());
        }

        public IActionResult Produtos()
        {
            contexto.Database.ExecuteSqlRaw("delete from produtos");
            contexto.Database.ExecuteSqlRaw("DBCC CHECKIDENT('produtos', RESEED, 0)");
            Random randnum = new Random();

            string[] vNomeProduto = { "Arroz", "Feijão", "Carne Bovina", "Carne Suína", "Frango", "Peixe Tilápia", "Alface", "Coca-Cola", "Sprite", "Detergente Veja",
                                      "Detergente Bombril", "Miojo de Copo", "Miojo Instantâneo", "Arroz Doce", "Peixe Salmão", };

            for (int i = 0; i < 20; i++)
            {
                Produto produto = new Produto();

                produto.nome = vNomeProduto[randnum.Next() % 15];
                produto.preco = randnum.Next(1, 200);
                produto.qtde = randnum.Next(1, 200);
                contexto.Produtos.Add(produto);
            }
            contexto.SaveChanges();

            return View(contexto.Produtos.OrderBy(o => o.id).ToList());
        }
    }
}

Controllers/OfertasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMercadoMVC.Models;

namespace WebMercadoMVC.Controllers
{
    public class OfertasController : Controller
    {
        private readonly Contexto _context;

        public OfertasController(Contexto context)
        {
            _context = context;
        }

        // GET: Ofertas
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Ofertas.Include(o => o.produto);
            return View(await contexto.ToListAsync());
        }

        // GET: Ofertas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ofertas == null)
            {
                return NotFound();
            }

            var oferta = await _context.Ofertas
                .Include(o => o.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (oferta == null)
            {
                return NotFound();
            }

            return View(oferta);
        }

        // GET: Ofertas/Create
        public IActionResult Create()
        {
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome");
            return View();
        }

        // POST: Ofertas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,produtoid,oferta,dataoferta")] Oferta oferta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(oferta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", oferta.produtoid);
            return View(oferta);
        }

        // GET: Ofertas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ofertas == null)
            {
                return NotFound();
            }

            var oferta = await _context.Ofertas.FindAsync(id);
            if (oferta == null)
            {
                return NotFound();
            }
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", oferta.produtoid);
            return View(oferta);
        }

        // POST: Ofertas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,produtoid,oferta,dataoferta")] Oferta oferta)
        {
            if (id != oferta.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oferta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfertaExists(oferta.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["produtoid"] = new SelectList(_context.Produtos, "id", "nome", oferta.produtoid);
            return View(oferta);
        }

        // GET: Ofertas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ofertas == null)
            {
                return NotFound();
            }

            var oferta = await _context.Ofertas
                .Include(o => o.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (oferta == null)
            {
                return NotFound();
            }

            return View(oferta);
        }

        // POST: Ofertas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ofertas == null)
            {
                return Problem("Entity set 'Contexto.Ofertas'  is null.");
            }
            var oferta = await _context.Ofertas.FindAsync(id);
            if (oferta != null)
            {
                _context.Ofertas.Remove(oferta);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfertaExists(int id)
        {
          return _context.Ofertas.Any(e => e.id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMercadoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMercadoMVC.styles.css" asp-append-version="true" />
</head>
<body class="bg-opacity-100 bg-warning">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">WebMercadoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light bg-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Opções
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Cliente</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produto</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compra</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Ofertas" asp-action="Index">Oferta</a></li>
                                <li><a class="nav-link text-dark" href="/Query/Pesquisa">Filtro por Nome (Cliente)</a></li>
                                <li><a class="nav-link text-dark" href="/Query/PesquisaProd">Filtro por Nome (Produto)</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item text-dark" href="#">Créditos</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Geração de Dados
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dados" asp-action="Clientes">Clientes</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dados" asp-action="Produtos">Produtos</a>
                            </ul>
                        </li>

                    </ul>
                    
                    <partial name="_LoginPartial"/>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark border-top footer text-muted">
        <div class="container text-white">
            &copy; Victor Masayuki Higuchi e Thiago de Carvalho Ferreira - 2023  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>