Models/Produto.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebMercadoMVC.Models
{
    [Table("Produtos")]
    public class Produto
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Id:")]
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Quantidade Disponível:")]
        public int qtde { get; set; }

        [Required(ErrorMessage = "Campo Obgrigatório")]
        [Display(Name = "Nome:")]
        [StringLength(30)]
        public string nome { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Preço:")]
        public float preco { get; set; }


    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMercadoMVC.Models;

namespace WebMercadoMVC.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly Contexto _context;

        public ProdutosController(Contexto context)
        {
            _context = context;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
              return View(await _context.Produtos.ToListAsync());
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,qtde,nome,preco")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,qtde,nome,preco")] Produto produto)
        {
            if (id != produto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produtos == null)
            {
                return Problem("Entity set 'Contexto.Produtos'  is null.");
            }
            var produto = await _context.Produtos.FindAsync(id);
            if (produto != null)
            {
                _context.Produtos.Remove(produto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
          return _context.Produtos.Any(e => e.id == id);
        }
    }
}

Controllers/QueryController.cs
using Microsoft.AspNetCore.Mvc;
using WebMercadoMVC.Models;

namespace WebMercadoMVC.Controllers
{
    public class QueryController : Controller
    {
        private readonly Contexto contexto;

        public QueryController(Contexto context)
        {
            contexto = context;
        }

        public IActionResult Clientes(string filtro)
        {
            List<Cliente> lista = new List<Cliente>();

            lista = contexto.Clientes.OrderBy(n => n.nome).Where(n => n.nome.Contains(filtro)).ToList();

            return View(lista);
        }
        public IActionResult Pesquisa()
        {
            return View();
        }

        public IActionResult Produtos(string filtro)
        {
            List<Produto> lista = new List<Produto>();

            lista = contexto.Produtos.OrderBy(n => n.nome).Where(n => n.nome.Contains(filtro)).ToList();

            return View(lista);
        }
        public IActionResult PesquisaProd()
        {
            return View();
        }
    }
}

Views/Produtos/Create.cshtml
@model WebMercadoMVC.Models.Produto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Adicionar Novos Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="preco" class="control-label"></label>
                <input asp-for="preco" class="form-control" />
                <span asp-validation-for="preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qtde" class="control-label"></label>
                <input asp-for="qtde" class="form-control" />
                <span asp-validation-for="qtde" class="text-danger"></span>
            </div>
            <br />
            <div>
                <input type="submit" value="Adicionar" class="btn btn-success" /> |
                <a input type="submit" class="btn btn-danger" asp-action="Index">Voltar</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Produtos/Delete.cshtml
@model WebMercadoMVC.Models.Produto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Remover Produto</h1>

<h3>Gostaria de remover este produto?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.qtde)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.qtde)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Remover" class="btn btn-secondary" /> |
        <a input type="submit" class="btn btn-danger" asp-action="Index">Voltar</a>
    </form>
</div>

Views/Produtos/Details.cshtml
@model WebMercadoMVC.Models.Produto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalhes do Produto</h1>

<div>
    <hr />
    <dl class="table">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.qtde)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.qtde)
        </dd>
    </dl>
</div>

<div>
    <a input type="submit" class="btn btn-primary btn-info" asp-action="Edit" asp-route-id="@Model?.id">Editar</a> |
    <a input type="submit" class="btn btn-danger" asp-action="Index">Voltar</a>
</div>

Views/Produtos/Edit.cshtml
@model WebMercadoMVC.Models.Produto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar Produtos</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="preco" class="control-label"></label>
                <input asp-for="preco" class="form-control" />
                <span asp-validation-for="preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qtde" class="control-label"></label>
                <input asp-for="qtde" class="form-control" />
                <span asp-validation-for="qtde" class="text-danger"></span>
            </div>
            <br />
            <div>
                <input type="submit" value="Salvar" class="btn btn-primary btn-success" /> |
                <a asp-action="Index" class="btn btn-danger">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Produtos/Index.cshtml
@model IEnumerable<WebMercadoMVC.Models.Produto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tabela de Produtos</h1>

<p>
    <a input type="submit" class="btn btn-success" asp-action="Create">Adicionar um Novo Produto</a>
</p>
<p>
    <a asp-controller="Query" asp-action="PesquisaProd" class="btn btn-secondary">Filtrar Produtos</a>
</p>

<table class="table bg-light">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.qtde)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.qtde)
                </td>
                <td>
                    <a input type="submit" class="btn btn-primary" asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                    <a input type="submit" class="btn btn-info" asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                    <a input type="submit" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.id">Remover</a>
                </td>
            </tr>
        }
    </tbody>
</table>